### ISSUE TITLE
Evidence Source: Wifi Network connected to

### ISSUE THREAD

**Issue by franciscolourenco** [dustinrue/ControlPlane#192]

**Comment by m-urban** [comment]
I have got two WiFi access points at my work place. When I connect to one of them, I'd also like to change my network location. Therefore, I need to know, which access point I am connected to. Is there a way I can accomplish this? "Nearby WiFi Network" doesn't quite cut it here, because both access points are close by.

Thanks!

**Comment by dustinrue** [comment]
Create BSSID based rules instead of SSID rules. BSSID is a number for a specific base station and not the network name.

**Comment by m-urban** [comment]
Apologies if I wasn't precise enough: I'd like to trigger a context change when I am *connected* to a specific access point, not when it is just in proximity.

**Comment by dustinrue** [comment]
WiFi evidence source, out of the box, will only use what you're currently connected to. It doesn't take into consideration what is around you IF you are connected to a network.
