### ISSUE TITLE
Multiple contexts breaks Wifi rules after sleep

### ISSUE THREAD

**Issue by rjcds** [dustinrue/ControlPlane#330]
With v1.4, I had a working setup that used Wifi SSID to select between contexts (Home and various work locations). This would retain the current context if the laptop woke from sleep, as long as the wifi SSID hadn't changed to one specified as a different context in the rules.

As of 1.5 and Multiple Contexts, after waking from laptop sleep, ControlPlane treats sleep (and lack of wifi) as a departure rule. So even though I haven't moved location, a simple sleep and wake will trigger departure and arrival rules for the same location. 

The only way I could fix this was to turn off multiple contexts. If multiple contexts is going to be permanent in the future, is there any way to fix this behaviour ?

Thanks very much

**Comment by joshkaplan** [comment]
Is there any update or workaround for this? Arriving/departing every time I open/close my laptop is a pretty large issue

**Comment by dustinrue** [comment]
This is a difficult issue that isn't limited to the multiple active contexts action. I have a routine setup that will unmount some external drives if my external monitor is disconnected. This action will trigger at sleep if I have the multiple active context option enabled or not. I can look at the particular evidence source I'm using but chances are very good that ControlPlane is being notified of a change in monitor state which triggers my depart action.

There are a number of reasons why this can't be resolved easily. Some evidence sources flush their state at sleep because not doing so results in a different class of issues. Good example is the power source evidence source. If it isn't flushed and reread at wake ControlPlane isn't aware that the power state changed (it's now on battery and not plugged in) between going to sleep and waking up. Some evidence sources, particularly WiFi, are picking up on system events at sleep or wake that result rule triggering. There is little to nothing that can be done here as the system is truly not connected to WiFi for a period of time and as far as ControlPlane is concern, its just doing its job.

**Comment by joshkaplan** [comment]
The larger issue seems to just be "sleep causes departures" for a lot of evidence sources. 

Makes total sense from a technical standpoint. Practically, however, it definitely limits ControlPlane's usefulness. It effectively means actions execute every time the computer sleeps/wakes. For any non-instantaneous actions, this is a significant issue. Additionally, some actions take too long to execute before system sleep, and therefore don't execute at all.

Example: I have "home" and "work" contexts. When I close my laptop to go to a meeting, my work-departure actions activate, and then my work-arrival rules activate when I begin the meeting, despite the fact I am still at "work." When I arrive "home" my work-departure rules have already fired (when I closed the laptop). 

The best idea I have for a solution is preventing evidence sources from updating once sleep is triggered, until the machine wakes back up. For some sources like Wi-Fi, the issue is even trickier, since it will still take a few seconds to reconnect. Perhaps building in specific "wake delays" could address. For example, Wi-Fi will ignore "no network connected" for 5 seconds after wake, before it begins updating normally.

**Comment by ravenz** [comment]
+1 for this
Not even "full" sleep but sometimes with just a screen off and Mac deciding to periodically turn off wifi can cause context switching
