### ISSUE TITLE
core location "always" picks default context

### ISSUE THREAD

**Issue by bjbarouch** [dustinrue/ControlPlane#387]
Latest version (1.5.3.). Latest Yosemite (10.10.1). New Mac, but this has been a continuous problem on previous versions, previous OS X versions, and previous Macs.

Create two contexts, 45 miles apart, say Home and Work. Create a third location, say Public, and default to it. Use Core Location as the only evidence source. Set the threshold for Home and Work at 70% each, set the overall threshold at 70%, default to Public. You'd figure if you were anywhere vaguely close to Home or Work, you'd get that one, but it just stays on Public, almost all of the time. You can have Enable multiple active contexts on or off, with no apparent effect.

**Comment by dustinrue** [comment]
You want to review your rules to ensure that you have set the confidence values properly. WiFi network is one of my main uses for ControlPlane and it's very solid. CoreLocation on the other hand is a mixed bag.

**Comment by bjbarouch** [comment]
Thanks.

As it turns out, the two main places I use my computer were purposely set
up to have the same WiFi BSSID. There are different wifi signals nearby,
and the software says "nearby", but it only seems to allow rule creation
for ones you are actually connected to. Am I missing something there?

At present I am getting reliable results when relying on the Mac power
adapter serial number, but of course that does not work when not plugged
in. To cover the on-battery scenario, I have recently switched to Bonjour
items that are different in my primary locations. I have not been using
that long enough yet to know if it is working well. What is the track
record with Bonjour-based rules?

With regard to geo-locations, is the geo-location in the Mac so bad that
locations tens of miles apart cannot be distinguished, so it just opts for
the default?

**Comment by dustinrue** [comment]
They have the same BSSID or SSID? The BSSID should be a globally “unique” value, most places don’t generally override this value if they even can.

Bonjour based rules should be pretty reliable. I used to use them but have eventually stopped because my need to use them went away.

The CoreLocation work in ControlPlane isn’t the best. I’d personally blame CP as much as CL though as CL can get really wonky at times. It’s bad enough that I rarely recommend it but some people have good luck with it.

Dustin

**Comment by bjbarouch** [comment]
Thank you, Dustin, for the utliity, and for taking the time to respond to
my questions.

Yes, I meant the SSID.

I'll go with power adpaters and Bonjour, based on your reply.

Should one be able to use *nearby* Wifi and not just wifi one is actually
connected to? That would be quite useful. How is that set? It only offers
up the currently connect Wifi in the dialog box.

Lastly, I am not sure I understand the confidence settings. On individual
rules, a low confidence setting means, do this even if the evidence is
slight, right? And a high setting means do not do this unless you are sure.
But even on power adpater, which is clearly yes or no, the opposite seems
to be the case. A low setting results in not picking that rule and a high
setting makes it work. I don't understand.

**Comment by dustinrue** [comment]
Try creating BSSID based rules unless you are working at a place with multiple access points using the same SSID. That gets trickier.

You can enable the ability to continuously scan for WiFi networks in the advanced settings page but doing so will often have a detrimental effect on WiFi performance because the system is constantly scanning for new WiFi networks.

Dustin

**Comment by bjbarouch** [comment]
Thanks again.
