### ISSUE TITLE
Couldn't mount that volume / triggered rule

### ISSUE THREAD

**Issue by Roger74** [dustinrue/ControlPlane#395]
Hi,

I'm not sure what I'm doing wrong, but the drive won't mount after sleep.
I'm getting this error -50 (in console)

Also, how can I make a rule, that should be triggered ONLY when computer goes to sleep AND the drive is unmounted?

Thnx,
Roger

**Comment by dustinrue** [comment]
First part, probably because the system is either not on the network yet (in the case of a network volume) or it isn't ready to attach any drives yet on USB. Either way, set the action to have a delay.

To make the second part work you need to play with the confidence values so that the context can only be entered when both conditions are met.

**Comment by pqd** [comment]
I have the same problem with a USB drive (even with a 30 seconds delay).

What is the syntax/form of the parameter of the Mount action when attempting to mount a USB drive?

The Unmount action works fine, and I assumed the parameter of the Mount action should be the same as for the Unmount action, but that will not work.

**Comment by pqd** [comment]
The thick plottens!
I noticed that the code in Source/MountAction.m calls FSMountServerVolumeSync. I don't think that function can be used to mount a local disk (i.e. a USB disk). If I read the reference documentation correctly it is used for mounting network volumes.
