### ISSUE TITLE
Bug with Default browser

### ISSUE THREAD

**Issue by anthonycampanelli72** [dustinrue/ControlPlane#449]
I have ControlPlane set to choose Chrome when my Mac is plugged in, and Safari when on battery power. However, after waking up from sleep, if I open a link it always opens in Chrome. It only starts using safari when I plug in and unplug. Is this a known issue, and how do I fix it?

**Comment by dustinrue** [comment]
ControlPlane asks OS X to notify if of when power source change has occurred. Because of how the evidence source works if you put the machine to sleep while plugged in and then unplug it before waking it ControlPlane won't know that a power source change as occurred and so it won't know that you're now on battery power.

I'll see if I can get ControlPlane to recheck the power source on wake.
