### ISSUE TITLE
Download option without Facebook?

### ISSUE THREAD

**Issue by Addlai** [dustinrue/ControlPlane#453]
For the binary download, you refer to MacUpdate, which requires that you log in with Facebook. I don't use Facebook as a matter of principle. Isn't there an alternative way to download the binary?

**Comment by meyer** [comment]
@Addlai there’s an tiny little “no thanks” link that will take you right to the [download page](https://www.macupdate.com/app/mac/39644/controlplane/download).

![image](https://cloud.githubusercontent.com/assets/13781/17461715/853f4148-5c4a-11e6-9c60-23a4abe04f35.png)

@dustinrue it might make sense to link directly to the download page? idk.

**Comment by dustinrue** [comment]
macupdate shouldn't be referred to anywhere on controlplaneapp.com. If you're finding it there please link me to the page it appears on and I'll remove it. I encourage people to no long download ControlPlane from macupdate because they started repackaging the app with an installer that installs adware.

**Comment by meyer** [comment]
@dustinrue Looks like MacUpdate is referenced in the sidebar of controlplaneapp.com and in this repo’s README.

![image](https://cloud.githubusercontent.com/assets/13781/17748812/f3fe416a-646f-11e6-9a81-7737f3112e9b.png)

**Comment by dustinrue** [comment]
Great, thanks!
